// ignore_for_file: non_constant_identifier_names
// ignore_for_file: camel_case_types
// ignore_for_file: prefer_single_quotes

// This file is automatically generated. DO NOT EDIT, all your changes would be lost.
import "dart:developer";

import "package:flutter/foundation.dart";

JsonConvert jsonConvert = JsonConvert();

class JsonConvert {
  T? convert<T>(dynamic value) {
    if (value == null) {
      return null;
    }
    return asT<T>(value);
  }

  List<T?>? convertList<T>(List<dynamic>? value) {
    if (value == null) {
      return null;
    }
    try {
      return value.map((dynamic e) => asT<T>(e)).toList();
    } on Exception catch (e, stackTrace) {
      if (kDebugMode) {
        log("asT<$T> $e $stackTrace");
      }
      return <T>[];
    }
  }

  List<T>? convertListNotNull<T>(dynamic value) {
    if (value == null) {
      return null;
    }
    try {
      return (value as List<dynamic>).map((dynamic e) => asT<T>(e)!).toList();
    } on Exception catch (e, stackTrace) {
      if (kDebugMode) {
        log("asT<$T> $e $stackTrace");
      }
      return <T>[];
    }
  }

  T? asT<T extends Object?>(dynamic value) {
    if (value is T) {
      return value;
    }
    final String type = T.toString();
    try {
      final String valueS = value.toString();
      if (type == "String") {
        return valueS as T;
      } else if (type == "int") {
        return _parseIntValue<T>(valueS);
      } else if (type == "double") {
        return double.parse(valueS) as T;
      } else if (type == "DateTime") {
        return DateTime.parse(valueS) as T;
      } else if (type == "bool") {
        return _parseBoolValue<T>(valueS);
      } else {
        return null;
      }
    } on Exception catch (e, stackTrace) {
      if (kDebugMode) {
        log("asT<$T> $e $stackTrace");
      }
      return null;
    }
  }

  T? _parseIntValue<T>(String valueS) {
    final int? intValue = int.tryParse(valueS);
    if (intValue == null) {
      return double.tryParse(valueS)?.toInt() as T?;
    }
    return intValue as T;
  }

  T _parseBoolValue<T>(String valueS) {
    if (valueS == "0" || valueS == "1") {
      return (valueS == "1") as T;
    }
    return (valueS == "true") as T;
  }
}
