// Mocks generated by Mockito 5.4.6 from annotations
// in esim_open_source/test/presentation/widgets/qr_scanner/qr_scanner_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:qr_code_scanner/src/qr_code_scanner.dart' as _i3;
import 'package:qr_code_scanner/src/types/barcode.dart' as _i5;
import 'package:qr_code_scanner/src/types/camera.dart' as _i6;
import 'package:qr_code_scanner/src/types/features.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSystemFeatures_0 extends _i1.SmartFake
    implements _i2.SystemFeatures {
  _FakeSystemFeatures_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [QRViewController].
///
/// See the documentation for Mockito's code generation for more information.
class MockQRViewController extends _i1.Mock implements _i3.QRViewController {
  MockQRViewController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.Barcode> get scannedDataStream => (super.noSuchMethod(
        Invocation.getter(#scannedDataStream),
        returnValue: _i4.Stream<_i5.Barcode>.empty(),
      ) as _i4.Stream<_i5.Barcode>);

  @override
  bool get hasPermissions => (super.noSuchMethod(
        Invocation.getter(#hasPermissions),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<_i6.CameraFacing> getCameraInfo() => (super.noSuchMethod(
        Invocation.method(
          #getCameraInfo,
          [],
        ),
        returnValue: _i4.Future<_i6.CameraFacing>.value(_i6.CameraFacing.back),
      ) as _i4.Future<_i6.CameraFacing>);

  @override
  _i4.Future<_i6.CameraFacing> flipCamera() => (super.noSuchMethod(
        Invocation.method(
          #flipCamera,
          [],
        ),
        returnValue: _i4.Future<_i6.CameraFacing>.value(_i6.CameraFacing.back),
      ) as _i4.Future<_i6.CameraFacing>);

  @override
  _i4.Future<bool?> getFlashStatus() => (super.noSuchMethod(
        Invocation.method(
          #getFlashStatus,
          [],
        ),
        returnValue: _i4.Future<bool?>.value(),
      ) as _i4.Future<bool?>);

  @override
  _i4.Future<void> toggleFlash() => (super.noSuchMethod(
        Invocation.method(
          #toggleFlash,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> pauseCamera() => (super.noSuchMethod(
        Invocation.method(
          #pauseCamera,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> stopCamera() => (super.noSuchMethod(
        Invocation.method(
          #stopCamera,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> resumeCamera() => (super.noSuchMethod(
        Invocation.method(
          #resumeCamera,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.SystemFeatures> getSystemFeatures() => (super.noSuchMethod(
        Invocation.method(
          #getSystemFeatures,
          [],
        ),
        returnValue: _i4.Future<_i2.SystemFeatures>.value(_FakeSystemFeatures_0(
          this,
          Invocation.method(
            #getSystemFeatures,
            [],
          ),
        )),
      ) as _i4.Future<_i2.SystemFeatures>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> scanInvert(bool? isScanInvert) => (super.noSuchMethod(
        Invocation.method(
          #scanInvert,
          [isScanInvert],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
