// Mocks generated by Mockito 5.4.6 from annotations
// in esim_open_source/test/data/data_source/home_local_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i10;

import 'package:esim_open_source/data/data_source/home_data_entities/bundle_category_entity.dart'
    as _i7;
import 'package:esim_open_source/data/data_source/home_data_entities/country_entity.dart'
    as _i6;
import 'package:esim_open_source/data/data_source/home_data_entities/home_data_entity.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:objectbox/objectbox.dart' as _i12;
import 'package:objectbox/src/native/box.dart' as _i2;
import 'package:objectbox/src/native/query/query.dart' as _i5;
import 'package:objectbox/src/store.dart' as _i8;
import 'package:objectbox/src/transaction.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBox_0<T1> extends _i1.SmartFake implements _i2.Box<T1> {
  _FakeBox_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_1<T> extends _i1.SmartFake implements _i3.Future<T> {
  _FakeFuture_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHomeDataEntity_2 extends _i1.SmartFake
    implements _i4.HomeDataEntity {
  _FakeHomeDataEntity_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQueryBuilder_3<T> extends _i1.SmartFake
    implements _i5.QueryBuilder<T> {
  _FakeQueryBuilder_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCountryEntity_4 extends _i1.SmartFake implements _i6.CountryEntity {
  _FakeCountryEntity_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBundleCategoryEntity_5 extends _i1.SmartFake
    implements _i7.BundleCategoryEntity {
  _FakeBundleCategoryEntity_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePropertyQuery_6<T> extends _i1.SmartFake
    implements _i5.PropertyQuery<T> {
  _FakePropertyQuery_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQuery_7<T> extends _i1.SmartFake implements _i5.Query<T> {
  _FakeQuery_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Store].
///
/// See the documentation for Mockito's code generation for more information.
class MockStore extends _i1.Mock implements _i8.Store {
  MockStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get directoryPath => (super.noSuchMethod(
        Invocation.getter(#directoryPath),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#directoryPath),
        ),
      ) as String);

  @override
  _i10.ByteData get reference => (super.noSuchMethod(
        Invocation.getter(#reference),
        returnValue: _i10.ByteData(0),
      ) as _i10.ByteData);

  @override
  bool isClosed() => (super.noSuchMethod(
        Invocation.method(
          #isClosed,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Box<T> box<T>() => (super.noSuchMethod(
        Invocation.method(
          #box,
          [],
        ),
        returnValue: _FakeBox_0<T>(
          this,
          Invocation.method(
            #box,
            [],
          ),
        ),
      ) as _i2.Box<T>);

  @override
  R runInTransaction<R>(
    _i11.TxMode? mode,
    R Function()? fn,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #runInTransaction,
          [
            mode,
            fn,
          ],
        ),
        returnValue: _i9.dummyValue<R>(
          this,
          Invocation.method(
            #runInTransaction,
            [
              mode,
              fn,
            ],
          ),
        ),
      ) as R);

  @override
  _i3.Future<R> runInTransactionAsync<R, P>(
    _i11.TxMode? mode,
    _i8.TxAsyncCallback<R, P>? callback,
    P? param,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #runInTransactionAsync,
          [
            mode,
            callback,
            param,
          ],
        ),
        returnValue: _i9.ifNotNull(
              _i9.dummyValueOrNull<R>(
                this,
                Invocation.method(
                  #runInTransactionAsync,
                  [
                    mode,
                    callback,
                    param,
                  ],
                ),
              ),
              (R v) => _i3.Future<R>.value(v),
            ) ??
            _FakeFuture_1<R>(
              this,
              Invocation.method(
                #runInTransactionAsync,
                [
                  mode,
                  callback,
                  param,
                ],
              ),
            ),
      ) as _i3.Future<R>);

  @override
  _i3.Future<R> runAsync<P, R>(
    _i8.RunAsyncCallback<P, R>? callback,
    P? param,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #runAsync,
          [
            callback,
            param,
          ],
        ),
        returnValue: _i9.ifNotNull(
              _i9.dummyValueOrNull<R>(
                this,
                Invocation.method(
                  #runAsync,
                  [
                    callback,
                    param,
                  ],
                ),
              ),
              (R v) => _i3.Future<R>.value(v),
            ) ??
            _FakeFuture_1<R>(
              this,
              Invocation.method(
                #runAsync,
                [
                  callback,
                  param,
                ],
              ),
            ),
      ) as _i3.Future<R>);

  @override
  bool awaitQueueCompletion() => (super.noSuchMethod(
        Invocation.method(
          #awaitQueueCompletion,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool awaitQueueSubmitted() => (super.noSuchMethod(
        Invocation.method(
          #awaitQueueSubmitted,
          [],
        ),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [Box].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeDataBox extends _i1.Mock implements _i2.Box<_i4.HomeDataEntity> {
  @override
  int put(
    _i4.HomeDataEntity? object, {
    _i2.PutMode? mode = _i2.PutMode.put,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [object],
          {#mode: mode},
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i3.Future<int> putAsync(
    _i4.HomeDataEntity? object, {
    _i2.PutMode? mode = _i2.PutMode.put,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putAsync,
          [object],
          {#mode: mode},
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<_i4.HomeDataEntity> putAndGetAsync(
    _i4.HomeDataEntity? object, {
    _i2.PutMode? mode = _i2.PutMode.put,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putAndGetAsync,
          [object],
          {#mode: mode},
        ),
        returnValue: _i3.Future<_i4.HomeDataEntity>.value(_FakeHomeDataEntity_2(
          this,
          Invocation.method(
            #putAndGetAsync,
            [object],
            {#mode: mode},
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i4.HomeDataEntity>.value(_FakeHomeDataEntity_2(
          this,
          Invocation.method(
            #putAndGetAsync,
            [object],
            {#mode: mode},
          ),
        )),
      ) as _i3.Future<_i4.HomeDataEntity>);

  @override
  _i3.Future<int> putQueuedAwaitResult(
    _i4.HomeDataEntity? object, {
    _i2.PutMode? mode = _i2.PutMode.put,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putQueuedAwaitResult,
          [object],
          {#mode: mode},
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  int putQueued(
    _i4.HomeDataEntity? object, {
    _i2.PutMode? mode = _i2.PutMode.put,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putQueued,
          [object],
          {#mode: mode},
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  List<int> putMany(
    List<_i4.HomeDataEntity>? objects, {
    _i2.PutMode? mode = _i2.PutMode.put,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putMany,
          [objects],
          {#mode: mode},
        ),
        returnValue: <int>[],
        returnValueForMissingStub: <int>[],
      ) as List<int>);

  @override
  _i3.Future<List<int>> putManyAsync(
    List<_i4.HomeDataEntity>? objects, {
    _i2.PutMode? mode = _i2.PutMode.put,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putManyAsync,
          [objects],
          {#mode: mode},
        ),
        returnValue: _i3.Future<List<int>>.value(<int>[]),
        returnValueForMissingStub: _i3.Future<List<int>>.value(<int>[]),
      ) as _i3.Future<List<int>>);

  @override
  _i3.Future<List<_i4.HomeDataEntity>> putAndGetManyAsync(
    List<_i4.HomeDataEntity>? objects, {
    _i2.PutMode? mode = _i2.PutMode.put,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putAndGetManyAsync,
          [objects],
          {#mode: mode},
        ),
        returnValue:
            _i3.Future<List<_i4.HomeDataEntity>>.value(<_i4.HomeDataEntity>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.HomeDataEntity>>.value(<_i4.HomeDataEntity>[]),
      ) as _i3.Future<List<_i4.HomeDataEntity>>);

  @override
  _i4.HomeDataEntity? get(int? id) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [id],
        ),
        returnValueForMissingStub: null,
      ) as _i4.HomeDataEntity?);

  @override
  _i3.Future<_i4.HomeDataEntity?> getAsync(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getAsync,
          [id],
        ),
        returnValue: _i3.Future<_i4.HomeDataEntity?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.HomeDataEntity?>.value(),
      ) as _i3.Future<_i4.HomeDataEntity?>);

  @override
  List<_i4.HomeDataEntity?> getMany(
    List<int>? ids, {
    bool? growableResult = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMany,
          [ids],
          {#growableResult: growableResult},
        ),
        returnValue: <_i4.HomeDataEntity?>[],
        returnValueForMissingStub: <_i4.HomeDataEntity?>[],
      ) as List<_i4.HomeDataEntity?>);

  @override
  _i3.Future<List<_i4.HomeDataEntity?>> getManyAsync(
    List<int>? ids, {
    bool? growableResult = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getManyAsync,
          [ids],
          {#growableResult: growableResult},
        ),
        returnValue: _i3.Future<List<_i4.HomeDataEntity?>>.value(
            <_i4.HomeDataEntity?>[]),
        returnValueForMissingStub: _i3.Future<List<_i4.HomeDataEntity?>>.value(
            <_i4.HomeDataEntity?>[]),
      ) as _i3.Future<List<_i4.HomeDataEntity?>>);

  @override
  List<_i4.HomeDataEntity> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: <_i4.HomeDataEntity>[],
        returnValueForMissingStub: <_i4.HomeDataEntity>[],
      ) as List<_i4.HomeDataEntity>);

  @override
  _i3.Future<List<_i4.HomeDataEntity>> getAllAsync() => (super.noSuchMethod(
        Invocation.method(
          #getAllAsync,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.HomeDataEntity>>.value(<_i4.HomeDataEntity>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.HomeDataEntity>>.value(<_i4.HomeDataEntity>[]),
      ) as _i3.Future<List<_i4.HomeDataEntity>>);

  @override
  _i5.QueryBuilder<_i4.HomeDataEntity> query(
          [_i5.Condition<_i4.HomeDataEntity>? qc]) =>
      (super.noSuchMethod(
        Invocation.method(
          #query,
          [qc],
        ),
        returnValue: _FakeQueryBuilder_3<_i4.HomeDataEntity>(
          this,
          Invocation.method(
            #query,
            [qc],
          ),
        ),
        returnValueForMissingStub: _FakeQueryBuilder_3<_i4.HomeDataEntity>(
          this,
          Invocation.method(
            #query,
            [qc],
          ),
        ),
      ) as _i5.QueryBuilder<_i4.HomeDataEntity>);

  @override
  int count({int? limit = 0}) => (super.noSuchMethod(
        Invocation.method(
          #count,
          [],
          {#limit: limit},
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool isEmpty() => (super.noSuchMethod(
        Invocation.method(
          #isEmpty,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool contains(int? id) => (super.noSuchMethod(
        Invocation.method(
          #contains,
          [id],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool containsMany(List<int>? ids) => (super.noSuchMethod(
        Invocation.method(
          #containsMany,
          [ids],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool remove(int? id) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [id],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.Future<bool> removeAsync(int? id) => (super.noSuchMethod(
        Invocation.method(
          #removeAsync,
          [id],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  int removeMany(List<int>? ids) => (super.noSuchMethod(
        Invocation.method(
          #removeMany,
          [ids],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i3.Future<int> removeManyAsync(List<int>? ids) => (super.noSuchMethod(
        Invocation.method(
          #removeManyAsync,
          [ids],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  int removeAll() => (super.noSuchMethod(
        Invocation.method(
          #removeAll,
          [],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i3.Future<int> removeAllAsync() => (super.noSuchMethod(
        Invocation.method(
          #removeAllAsync,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}

/// A class which mocks [Box].
///
/// See the documentation for Mockito's code generation for more information.
class MockCountryBox extends _i1.Mock implements _i2.Box<_i6.CountryEntity> {
  @override
  int put(
    _i6.CountryEntity? object, {
    _i2.PutMode? mode = _i2.PutMode.put,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [object],
          {#mode: mode},
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i3.Future<int> putAsync(
    _i6.CountryEntity? object, {
    _i2.PutMode? mode = _i2.PutMode.put,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putAsync,
          [object],
          {#mode: mode},
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<_i6.CountryEntity> putAndGetAsync(
    _i6.CountryEntity? object, {
    _i2.PutMode? mode = _i2.PutMode.put,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putAndGetAsync,
          [object],
          {#mode: mode},
        ),
        returnValue: _i3.Future<_i6.CountryEntity>.value(_FakeCountryEntity_4(
          this,
          Invocation.method(
            #putAndGetAsync,
            [object],
            {#mode: mode},
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i6.CountryEntity>.value(_FakeCountryEntity_4(
          this,
          Invocation.method(
            #putAndGetAsync,
            [object],
            {#mode: mode},
          ),
        )),
      ) as _i3.Future<_i6.CountryEntity>);

  @override
  _i3.Future<int> putQueuedAwaitResult(
    _i6.CountryEntity? object, {
    _i2.PutMode? mode = _i2.PutMode.put,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putQueuedAwaitResult,
          [object],
          {#mode: mode},
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  int putQueued(
    _i6.CountryEntity? object, {
    _i2.PutMode? mode = _i2.PutMode.put,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putQueued,
          [object],
          {#mode: mode},
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  List<int> putMany(
    List<_i6.CountryEntity>? objects, {
    _i2.PutMode? mode = _i2.PutMode.put,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putMany,
          [objects],
          {#mode: mode},
        ),
        returnValue: <int>[],
        returnValueForMissingStub: <int>[],
      ) as List<int>);

  @override
  _i3.Future<List<int>> putManyAsync(
    List<_i6.CountryEntity>? objects, {
    _i2.PutMode? mode = _i2.PutMode.put,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putManyAsync,
          [objects],
          {#mode: mode},
        ),
        returnValue: _i3.Future<List<int>>.value(<int>[]),
        returnValueForMissingStub: _i3.Future<List<int>>.value(<int>[]),
      ) as _i3.Future<List<int>>);

  @override
  _i3.Future<List<_i6.CountryEntity>> putAndGetManyAsync(
    List<_i6.CountryEntity>? objects, {
    _i2.PutMode? mode = _i2.PutMode.put,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putAndGetManyAsync,
          [objects],
          {#mode: mode},
        ),
        returnValue:
            _i3.Future<List<_i6.CountryEntity>>.value(<_i6.CountryEntity>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i6.CountryEntity>>.value(<_i6.CountryEntity>[]),
      ) as _i3.Future<List<_i6.CountryEntity>>);

  @override
  _i6.CountryEntity? get(int? id) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [id],
        ),
        returnValueForMissingStub: null,
      ) as _i6.CountryEntity?);

  @override
  _i3.Future<_i6.CountryEntity?> getAsync(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getAsync,
          [id],
        ),
        returnValue: _i3.Future<_i6.CountryEntity?>.value(),
        returnValueForMissingStub: _i3.Future<_i6.CountryEntity?>.value(),
      ) as _i3.Future<_i6.CountryEntity?>);

  @override
  List<_i6.CountryEntity?> getMany(
    List<int>? ids, {
    bool? growableResult = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMany,
          [ids],
          {#growableResult: growableResult},
        ),
        returnValue: <_i6.CountryEntity?>[],
        returnValueForMissingStub: <_i6.CountryEntity?>[],
      ) as List<_i6.CountryEntity?>);

  @override
  _i3.Future<List<_i6.CountryEntity?>> getManyAsync(
    List<int>? ids, {
    bool? growableResult = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getManyAsync,
          [ids],
          {#growableResult: growableResult},
        ),
        returnValue:
            _i3.Future<List<_i6.CountryEntity?>>.value(<_i6.CountryEntity?>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i6.CountryEntity?>>.value(<_i6.CountryEntity?>[]),
      ) as _i3.Future<List<_i6.CountryEntity?>>);

  @override
  List<_i6.CountryEntity> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: <_i6.CountryEntity>[],
        returnValueForMissingStub: <_i6.CountryEntity>[],
      ) as List<_i6.CountryEntity>);

  @override
  _i3.Future<List<_i6.CountryEntity>> getAllAsync() => (super.noSuchMethod(
        Invocation.method(
          #getAllAsync,
          [],
        ),
        returnValue:
            _i3.Future<List<_i6.CountryEntity>>.value(<_i6.CountryEntity>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i6.CountryEntity>>.value(<_i6.CountryEntity>[]),
      ) as _i3.Future<List<_i6.CountryEntity>>);

  @override
  _i5.QueryBuilder<_i6.CountryEntity> query(
          [_i5.Condition<_i6.CountryEntity>? qc]) =>
      (super.noSuchMethod(
        Invocation.method(
          #query,
          [qc],
        ),
        returnValue: _FakeQueryBuilder_3<_i6.CountryEntity>(
          this,
          Invocation.method(
            #query,
            [qc],
          ),
        ),
        returnValueForMissingStub: _FakeQueryBuilder_3<_i6.CountryEntity>(
          this,
          Invocation.method(
            #query,
            [qc],
          ),
        ),
      ) as _i5.QueryBuilder<_i6.CountryEntity>);

  @override
  int count({int? limit = 0}) => (super.noSuchMethod(
        Invocation.method(
          #count,
          [],
          {#limit: limit},
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool isEmpty() => (super.noSuchMethod(
        Invocation.method(
          #isEmpty,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool contains(int? id) => (super.noSuchMethod(
        Invocation.method(
          #contains,
          [id],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool containsMany(List<int>? ids) => (super.noSuchMethod(
        Invocation.method(
          #containsMany,
          [ids],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool remove(int? id) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [id],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.Future<bool> removeAsync(int? id) => (super.noSuchMethod(
        Invocation.method(
          #removeAsync,
          [id],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  int removeMany(List<int>? ids) => (super.noSuchMethod(
        Invocation.method(
          #removeMany,
          [ids],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i3.Future<int> removeManyAsync(List<int>? ids) => (super.noSuchMethod(
        Invocation.method(
          #removeManyAsync,
          [ids],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  int removeAll() => (super.noSuchMethod(
        Invocation.method(
          #removeAll,
          [],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i3.Future<int> removeAllAsync() => (super.noSuchMethod(
        Invocation.method(
          #removeAllAsync,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}

/// A class which mocks [Box].
///
/// See the documentation for Mockito's code generation for more information.
class MockBundleCategoryBox extends _i1.Mock
    implements _i2.Box<_i7.BundleCategoryEntity> {
  @override
  int put(
    _i7.BundleCategoryEntity? object, {
    _i2.PutMode? mode = _i2.PutMode.put,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [object],
          {#mode: mode},
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i3.Future<int> putAsync(
    _i7.BundleCategoryEntity? object, {
    _i2.PutMode? mode = _i2.PutMode.put,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putAsync,
          [object],
          {#mode: mode},
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<_i7.BundleCategoryEntity> putAndGetAsync(
    _i7.BundleCategoryEntity? object, {
    _i2.PutMode? mode = _i2.PutMode.put,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putAndGetAsync,
          [object],
          {#mode: mode},
        ),
        returnValue: _i3.Future<_i7.BundleCategoryEntity>.value(
            _FakeBundleCategoryEntity_5(
          this,
          Invocation.method(
            #putAndGetAsync,
            [object],
            {#mode: mode},
          ),
        )),
        returnValueForMissingStub: _i3.Future<_i7.BundleCategoryEntity>.value(
            _FakeBundleCategoryEntity_5(
          this,
          Invocation.method(
            #putAndGetAsync,
            [object],
            {#mode: mode},
          ),
        )),
      ) as _i3.Future<_i7.BundleCategoryEntity>);

  @override
  _i3.Future<int> putQueuedAwaitResult(
    _i7.BundleCategoryEntity? object, {
    _i2.PutMode? mode = _i2.PutMode.put,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putQueuedAwaitResult,
          [object],
          {#mode: mode},
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  int putQueued(
    _i7.BundleCategoryEntity? object, {
    _i2.PutMode? mode = _i2.PutMode.put,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putQueued,
          [object],
          {#mode: mode},
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  List<int> putMany(
    List<_i7.BundleCategoryEntity>? objects, {
    _i2.PutMode? mode = _i2.PutMode.put,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putMany,
          [objects],
          {#mode: mode},
        ),
        returnValue: <int>[],
        returnValueForMissingStub: <int>[],
      ) as List<int>);

  @override
  _i3.Future<List<int>> putManyAsync(
    List<_i7.BundleCategoryEntity>? objects, {
    _i2.PutMode? mode = _i2.PutMode.put,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putManyAsync,
          [objects],
          {#mode: mode},
        ),
        returnValue: _i3.Future<List<int>>.value(<int>[]),
        returnValueForMissingStub: _i3.Future<List<int>>.value(<int>[]),
      ) as _i3.Future<List<int>>);

  @override
  _i3.Future<List<_i7.BundleCategoryEntity>> putAndGetManyAsync(
    List<_i7.BundleCategoryEntity>? objects, {
    _i2.PutMode? mode = _i2.PutMode.put,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putAndGetManyAsync,
          [objects],
          {#mode: mode},
        ),
        returnValue: _i3.Future<List<_i7.BundleCategoryEntity>>.value(
            <_i7.BundleCategoryEntity>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i7.BundleCategoryEntity>>.value(
                <_i7.BundleCategoryEntity>[]),
      ) as _i3.Future<List<_i7.BundleCategoryEntity>>);

  @override
  _i7.BundleCategoryEntity? get(int? id) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [id],
        ),
        returnValueForMissingStub: null,
      ) as _i7.BundleCategoryEntity?);

  @override
  _i3.Future<_i7.BundleCategoryEntity?> getAsync(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAsync,
          [id],
        ),
        returnValue: _i3.Future<_i7.BundleCategoryEntity?>.value(),
        returnValueForMissingStub:
            _i3.Future<_i7.BundleCategoryEntity?>.value(),
      ) as _i3.Future<_i7.BundleCategoryEntity?>);

  @override
  List<_i7.BundleCategoryEntity?> getMany(
    List<int>? ids, {
    bool? growableResult = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMany,
          [ids],
          {#growableResult: growableResult},
        ),
        returnValue: <_i7.BundleCategoryEntity?>[],
        returnValueForMissingStub: <_i7.BundleCategoryEntity?>[],
      ) as List<_i7.BundleCategoryEntity?>);

  @override
  _i3.Future<List<_i7.BundleCategoryEntity?>> getManyAsync(
    List<int>? ids, {
    bool? growableResult = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getManyAsync,
          [ids],
          {#growableResult: growableResult},
        ),
        returnValue: _i3.Future<List<_i7.BundleCategoryEntity?>>.value(
            <_i7.BundleCategoryEntity?>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i7.BundleCategoryEntity?>>.value(
                <_i7.BundleCategoryEntity?>[]),
      ) as _i3.Future<List<_i7.BundleCategoryEntity?>>);

  @override
  List<_i7.BundleCategoryEntity> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: <_i7.BundleCategoryEntity>[],
        returnValueForMissingStub: <_i7.BundleCategoryEntity>[],
      ) as List<_i7.BundleCategoryEntity>);

  @override
  _i3.Future<List<_i7.BundleCategoryEntity>> getAllAsync() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllAsync,
          [],
        ),
        returnValue: _i3.Future<List<_i7.BundleCategoryEntity>>.value(
            <_i7.BundleCategoryEntity>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i7.BundleCategoryEntity>>.value(
                <_i7.BundleCategoryEntity>[]),
      ) as _i3.Future<List<_i7.BundleCategoryEntity>>);

  @override
  _i5.QueryBuilder<_i7.BundleCategoryEntity> query(
          [_i5.Condition<_i7.BundleCategoryEntity>? qc]) =>
      (super.noSuchMethod(
        Invocation.method(
          #query,
          [qc],
        ),
        returnValue: _FakeQueryBuilder_3<_i7.BundleCategoryEntity>(
          this,
          Invocation.method(
            #query,
            [qc],
          ),
        ),
        returnValueForMissingStub:
            _FakeQueryBuilder_3<_i7.BundleCategoryEntity>(
          this,
          Invocation.method(
            #query,
            [qc],
          ),
        ),
      ) as _i5.QueryBuilder<_i7.BundleCategoryEntity>);

  @override
  int count({int? limit = 0}) => (super.noSuchMethod(
        Invocation.method(
          #count,
          [],
          {#limit: limit},
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool isEmpty() => (super.noSuchMethod(
        Invocation.method(
          #isEmpty,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool contains(int? id) => (super.noSuchMethod(
        Invocation.method(
          #contains,
          [id],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool containsMany(List<int>? ids) => (super.noSuchMethod(
        Invocation.method(
          #containsMany,
          [ids],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool remove(int? id) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [id],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.Future<bool> removeAsync(int? id) => (super.noSuchMethod(
        Invocation.method(
          #removeAsync,
          [id],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  int removeMany(List<int>? ids) => (super.noSuchMethod(
        Invocation.method(
          #removeMany,
          [ids],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i3.Future<int> removeManyAsync(List<int>? ids) => (super.noSuchMethod(
        Invocation.method(
          #removeManyAsync,
          [ids],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  int removeAll() => (super.noSuchMethod(
        Invocation.method(
          #removeAll,
          [],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i3.Future<int> removeAllAsync() => (super.noSuchMethod(
        Invocation.method(
          #removeAllAsync,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}

/// A class which mocks [Query].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeDataQuery extends _i1.Mock
    implements _i5.Query<_i4.HomeDataEntity> {
  @override
  int get entityId => (super.noSuchMethod(
        Invocation.getter(#entityId),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  set offset(int? offset) => super.noSuchMethod(
        Invocation.setter(
          #offset,
          offset,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set limit(int? limit) => super.noSuchMethod(
        Invocation.setter(
          #limit,
          limit,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int count() => (super.noSuchMethod(
        Invocation.method(
          #count,
          [],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int remove() => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i3.Future<int> removeAsync() => (super.noSuchMethod(
        Invocation.method(
          #removeAsync,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<_i4.HomeDataEntity?> findFirstAsync() => (super.noSuchMethod(
        Invocation.method(
          #findFirstAsync,
          [],
        ),
        returnValue: _i3.Future<_i4.HomeDataEntity?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.HomeDataEntity?>.value(),
      ) as _i3.Future<_i4.HomeDataEntity?>);

  @override
  _i3.Future<_i4.HomeDataEntity?> findUniqueAsync() => (super.noSuchMethod(
        Invocation.method(
          #findUniqueAsync,
          [],
        ),
        returnValue: _i3.Future<_i4.HomeDataEntity?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.HomeDataEntity?>.value(),
      ) as _i3.Future<_i4.HomeDataEntity?>);

  @override
  List<int> findIds() => (super.noSuchMethod(
        Invocation.method(
          #findIds,
          [],
        ),
        returnValue: <int>[],
        returnValueForMissingStub: <int>[],
      ) as List<int>);

  @override
  _i3.Future<List<int>> findIdsAsync() => (super.noSuchMethod(
        Invocation.method(
          #findIdsAsync,
          [],
        ),
        returnValue: _i3.Future<List<int>>.value(<int>[]),
        returnValueForMissingStub: _i3.Future<List<int>>.value(<int>[]),
      ) as _i3.Future<List<int>>);

  @override
  List<_i4.HomeDataEntity> find() => (super.noSuchMethod(
        Invocation.method(
          #find,
          [],
        ),
        returnValue: <_i4.HomeDataEntity>[],
        returnValueForMissingStub: <_i4.HomeDataEntity>[],
      ) as List<_i4.HomeDataEntity>);

  @override
  _i3.Future<List<_i4.HomeDataEntity>> findAsync() => (super.noSuchMethod(
        Invocation.method(
          #findAsync,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.HomeDataEntity>>.value(<_i4.HomeDataEntity>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.HomeDataEntity>>.value(<_i4.HomeDataEntity>[]),
      ) as _i3.Future<List<_i4.HomeDataEntity>>);

  @override
  List<_i12.IdWithScore> findIdsWithScores() => (super.noSuchMethod(
        Invocation.method(
          #findIdsWithScores,
          [],
        ),
        returnValue: <_i12.IdWithScore>[],
        returnValueForMissingStub: <_i12.IdWithScore>[],
      ) as List<_i12.IdWithScore>);

  @override
  _i3.Future<List<_i12.IdWithScore>> findIdsWithScoresAsync() =>
      (super.noSuchMethod(
        Invocation.method(
          #findIdsWithScoresAsync,
          [],
        ),
        returnValue:
            _i3.Future<List<_i12.IdWithScore>>.value(<_i12.IdWithScore>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i12.IdWithScore>>.value(<_i12.IdWithScore>[]),
      ) as _i3.Future<List<_i12.IdWithScore>>);

  @override
  List<_i12.ObjectWithScore<_i4.HomeDataEntity>> findWithScores() =>
      (super.noSuchMethod(
        Invocation.method(
          #findWithScores,
          [],
        ),
        returnValue: <_i12.ObjectWithScore<_i4.HomeDataEntity>>[],
        returnValueForMissingStub: <_i12.ObjectWithScore<_i4.HomeDataEntity>>[],
      ) as List<_i12.ObjectWithScore<_i4.HomeDataEntity>>);

  @override
  _i3.Future<
      List<
          _i12.ObjectWithScore<_i4.HomeDataEntity>>> findWithScoresAsync() =>
      (super.noSuchMethod(
        Invocation.method(
          #findWithScoresAsync,
          [],
        ),
        returnValue:
            _i3.Future<List<_i12.ObjectWithScore<_i4.HomeDataEntity>>>.value(
                <_i12.ObjectWithScore<_i4.HomeDataEntity>>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i12.ObjectWithScore<_i4.HomeDataEntity>>>.value(
                <_i12.ObjectWithScore<_i4.HomeDataEntity>>[]),
      ) as _i3.Future<List<_i12.ObjectWithScore<_i4.HomeDataEntity>>>);

  @override
  _i3.Stream<_i4.HomeDataEntity> stream() => (super.noSuchMethod(
        Invocation.method(
          #stream,
          [],
        ),
        returnValue: _i3.Stream<_i4.HomeDataEntity>.empty(),
        returnValueForMissingStub: _i3.Stream<_i4.HomeDataEntity>.empty(),
      ) as _i3.Stream<_i4.HomeDataEntity>);

  @override
  String describe() => (super.noSuchMethod(
        Invocation.method(
          #describe,
          [],
        ),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.method(
            #describe,
            [],
          ),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.method(
            #describe,
            [],
          ),
        ),
      ) as String);

  @override
  String describeParameters() => (super.noSuchMethod(
        Invocation.method(
          #describeParameters,
          [],
        ),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.method(
            #describeParameters,
            [],
          ),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.method(
            #describeParameters,
            [],
          ),
        ),
      ) as String);

  @override
  _i5.PropertyQuery<DartType> property<DartType>(
          _i5.QueryProperty<_i4.HomeDataEntity, DartType>? prop) =>
      (super.noSuchMethod(
        Invocation.method(
          #property,
          [prop],
        ),
        returnValue: _FakePropertyQuery_6<DartType>(
          this,
          Invocation.method(
            #property,
            [prop],
          ),
        ),
        returnValueForMissingStub: _FakePropertyQuery_6<DartType>(
          this,
          Invocation.method(
            #property,
            [prop],
          ),
        ),
      ) as _i5.PropertyQuery<DartType>);
}

/// A class which mocks [Query].
///
/// See the documentation for Mockito's code generation for more information.
class MockCountryQuery extends _i1.Mock
    implements _i5.Query<_i6.CountryEntity> {
  @override
  int get entityId => (super.noSuchMethod(
        Invocation.getter(#entityId),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  set offset(int? offset) => super.noSuchMethod(
        Invocation.setter(
          #offset,
          offset,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set limit(int? limit) => super.noSuchMethod(
        Invocation.setter(
          #limit,
          limit,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int count() => (super.noSuchMethod(
        Invocation.method(
          #count,
          [],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int remove() => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i3.Future<int> removeAsync() => (super.noSuchMethod(
        Invocation.method(
          #removeAsync,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<_i6.CountryEntity?> findFirstAsync() => (super.noSuchMethod(
        Invocation.method(
          #findFirstAsync,
          [],
        ),
        returnValue: _i3.Future<_i6.CountryEntity?>.value(),
        returnValueForMissingStub: _i3.Future<_i6.CountryEntity?>.value(),
      ) as _i3.Future<_i6.CountryEntity?>);

  @override
  _i3.Future<_i6.CountryEntity?> findUniqueAsync() => (super.noSuchMethod(
        Invocation.method(
          #findUniqueAsync,
          [],
        ),
        returnValue: _i3.Future<_i6.CountryEntity?>.value(),
        returnValueForMissingStub: _i3.Future<_i6.CountryEntity?>.value(),
      ) as _i3.Future<_i6.CountryEntity?>);

  @override
  List<int> findIds() => (super.noSuchMethod(
        Invocation.method(
          #findIds,
          [],
        ),
        returnValue: <int>[],
        returnValueForMissingStub: <int>[],
      ) as List<int>);

  @override
  _i3.Future<List<int>> findIdsAsync() => (super.noSuchMethod(
        Invocation.method(
          #findIdsAsync,
          [],
        ),
        returnValue: _i3.Future<List<int>>.value(<int>[]),
        returnValueForMissingStub: _i3.Future<List<int>>.value(<int>[]),
      ) as _i3.Future<List<int>>);

  @override
  List<_i6.CountryEntity> find() => (super.noSuchMethod(
        Invocation.method(
          #find,
          [],
        ),
        returnValue: <_i6.CountryEntity>[],
        returnValueForMissingStub: <_i6.CountryEntity>[],
      ) as List<_i6.CountryEntity>);

  @override
  _i3.Future<List<_i6.CountryEntity>> findAsync() => (super.noSuchMethod(
        Invocation.method(
          #findAsync,
          [],
        ),
        returnValue:
            _i3.Future<List<_i6.CountryEntity>>.value(<_i6.CountryEntity>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i6.CountryEntity>>.value(<_i6.CountryEntity>[]),
      ) as _i3.Future<List<_i6.CountryEntity>>);

  @override
  List<_i12.IdWithScore> findIdsWithScores() => (super.noSuchMethod(
        Invocation.method(
          #findIdsWithScores,
          [],
        ),
        returnValue: <_i12.IdWithScore>[],
        returnValueForMissingStub: <_i12.IdWithScore>[],
      ) as List<_i12.IdWithScore>);

  @override
  _i3.Future<List<_i12.IdWithScore>> findIdsWithScoresAsync() =>
      (super.noSuchMethod(
        Invocation.method(
          #findIdsWithScoresAsync,
          [],
        ),
        returnValue:
            _i3.Future<List<_i12.IdWithScore>>.value(<_i12.IdWithScore>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i12.IdWithScore>>.value(<_i12.IdWithScore>[]),
      ) as _i3.Future<List<_i12.IdWithScore>>);

  @override
  List<_i12.ObjectWithScore<_i6.CountryEntity>> findWithScores() =>
      (super.noSuchMethod(
        Invocation.method(
          #findWithScores,
          [],
        ),
        returnValue: <_i12.ObjectWithScore<_i6.CountryEntity>>[],
        returnValueForMissingStub: <_i12.ObjectWithScore<_i6.CountryEntity>>[],
      ) as List<_i12.ObjectWithScore<_i6.CountryEntity>>);

  @override
  _i3.Future<List<_i12.ObjectWithScore<_i6.CountryEntity>>>
      findWithScoresAsync() => (super.noSuchMethod(
            Invocation.method(
              #findWithScoresAsync,
              [],
            ),
            returnValue:
                _i3.Future<List<_i12.ObjectWithScore<_i6.CountryEntity>>>.value(
                    <_i12.ObjectWithScore<_i6.CountryEntity>>[]),
            returnValueForMissingStub:
                _i3.Future<List<_i12.ObjectWithScore<_i6.CountryEntity>>>.value(
                    <_i12.ObjectWithScore<_i6.CountryEntity>>[]),
          ) as _i3.Future<List<_i12.ObjectWithScore<_i6.CountryEntity>>>);

  @override
  _i3.Stream<_i6.CountryEntity> stream() => (super.noSuchMethod(
        Invocation.method(
          #stream,
          [],
        ),
        returnValue: _i3.Stream<_i6.CountryEntity>.empty(),
        returnValueForMissingStub: _i3.Stream<_i6.CountryEntity>.empty(),
      ) as _i3.Stream<_i6.CountryEntity>);

  @override
  String describe() => (super.noSuchMethod(
        Invocation.method(
          #describe,
          [],
        ),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.method(
            #describe,
            [],
          ),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.method(
            #describe,
            [],
          ),
        ),
      ) as String);

  @override
  String describeParameters() => (super.noSuchMethod(
        Invocation.method(
          #describeParameters,
          [],
        ),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.method(
            #describeParameters,
            [],
          ),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.method(
            #describeParameters,
            [],
          ),
        ),
      ) as String);

  @override
  _i5.PropertyQuery<DartType> property<DartType>(
          _i5.QueryProperty<_i6.CountryEntity, DartType>? prop) =>
      (super.noSuchMethod(
        Invocation.method(
          #property,
          [prop],
        ),
        returnValue: _FakePropertyQuery_6<DartType>(
          this,
          Invocation.method(
            #property,
            [prop],
          ),
        ),
        returnValueForMissingStub: _FakePropertyQuery_6<DartType>(
          this,
          Invocation.method(
            #property,
            [prop],
          ),
        ),
      ) as _i5.PropertyQuery<DartType>);
}

/// A class which mocks [QueryBuilder].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeDataQueryBuilder extends _i1.Mock
    implements _i5.QueryBuilder<_i4.HomeDataEntity> {
  @override
  _i5.Query<_i4.HomeDataEntity> build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: _FakeQuery_7<_i4.HomeDataEntity>(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeQuery_7<_i4.HomeDataEntity>(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
      ) as _i5.Query<_i4.HomeDataEntity>);

  @override
  _i3.Stream<_i5.Query<_i4.HomeDataEntity>> watch(
          {bool? triggerImmediately = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #watch,
          [],
          {#triggerImmediately: triggerImmediately},
        ),
        returnValue: _i3.Stream<_i5.Query<_i4.HomeDataEntity>>.empty(),
        returnValueForMissingStub:
            _i3.Stream<_i5.Query<_i4.HomeDataEntity>>.empty(),
      ) as _i3.Stream<_i5.Query<_i4.HomeDataEntity>>);

  @override
  _i5.QueryBuilder<_i4.HomeDataEntity> order<D>(
    _i5.QueryProperty<_i4.HomeDataEntity, D>? p, {
    int? flags = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #order,
          [p],
          {#flags: flags},
        ),
        returnValue: _FakeQueryBuilder_3<_i4.HomeDataEntity>(
          this,
          Invocation.method(
            #order,
            [p],
            {#flags: flags},
          ),
        ),
        returnValueForMissingStub: _FakeQueryBuilder_3<_i4.HomeDataEntity>(
          this,
          Invocation.method(
            #order,
            [p],
            {#flags: flags},
          ),
        ),
      ) as _i5.QueryBuilder<_i4.HomeDataEntity>);

  @override
  link<TargetEntityT>(
    _i5.QueryRelationToOne<_i4.HomeDataEntity, TargetEntityT>? rel, [
    _i5.Condition<TargetEntityT>? qc,
  ]) =>
      throw UnsupportedError(
          r'"link" cannot be used without a mockito fallback generator.');

  @override
  backlink<SourceEntityT>(
    _i5.QueryRelationToOne<SourceEntityT, _i4.HomeDataEntity>? rel, [
    _i5.Condition<SourceEntityT>? qc,
  ]) =>
      throw UnsupportedError(
          r'"backlink" cannot be used without a mockito fallback generator.');

  @override
  linkMany<TargetEntityT>(
    _i5.QueryRelationToMany<_i4.HomeDataEntity, TargetEntityT>? rel, [
    _i5.Condition<TargetEntityT>? qc,
  ]) =>
      throw UnsupportedError(
          r'"linkMany" cannot be used without a mockito fallback generator.');

  @override
  backlinkMany<SourceEntityT>(
    _i5.QueryRelationToMany<SourceEntityT, _i4.HomeDataEntity>? rel, [
    _i5.Condition<SourceEntityT>? qc,
  ]) =>
      throw UnsupportedError(
          r'"backlinkMany" cannot be used without a mockito fallback generator.');
}

/// A class which mocks [QueryBuilder].
///
/// See the documentation for Mockito's code generation for more information.
class MockCountryQueryBuilder extends _i1.Mock
    implements _i5.QueryBuilder<_i6.CountryEntity> {
  @override
  _i5.Query<_i6.CountryEntity> build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: _FakeQuery_7<_i6.CountryEntity>(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeQuery_7<_i6.CountryEntity>(
          this,
          Invocation.method(
            #build,
            [],
          ),
        ),
      ) as _i5.Query<_i6.CountryEntity>);

  @override
  _i3.Stream<_i5.Query<_i6.CountryEntity>> watch(
          {bool? triggerImmediately = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #watch,
          [],
          {#triggerImmediately: triggerImmediately},
        ),
        returnValue: _i3.Stream<_i5.Query<_i6.CountryEntity>>.empty(),
        returnValueForMissingStub:
            _i3.Stream<_i5.Query<_i6.CountryEntity>>.empty(),
      ) as _i3.Stream<_i5.Query<_i6.CountryEntity>>);

  @override
  _i5.QueryBuilder<_i6.CountryEntity> order<D>(
    _i5.QueryProperty<_i6.CountryEntity, D>? p, {
    int? flags = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #order,
          [p],
          {#flags: flags},
        ),
        returnValue: _FakeQueryBuilder_3<_i6.CountryEntity>(
          this,
          Invocation.method(
            #order,
            [p],
            {#flags: flags},
          ),
        ),
        returnValueForMissingStub: _FakeQueryBuilder_3<_i6.CountryEntity>(
          this,
          Invocation.method(
            #order,
            [p],
            {#flags: flags},
          ),
        ),
      ) as _i5.QueryBuilder<_i6.CountryEntity>);

  @override
  link<TargetEntityT>(
    _i5.QueryRelationToOne<_i6.CountryEntity, TargetEntityT>? rel, [
    _i5.Condition<TargetEntityT>? qc,
  ]) =>
      throw UnsupportedError(
          r'"link" cannot be used without a mockito fallback generator.');

  @override
  backlink<SourceEntityT>(
    _i5.QueryRelationToOne<SourceEntityT, _i6.CountryEntity>? rel, [
    _i5.Condition<SourceEntityT>? qc,
  ]) =>
      throw UnsupportedError(
          r'"backlink" cannot be used without a mockito fallback generator.');

  @override
  linkMany<TargetEntityT>(
    _i5.QueryRelationToMany<_i6.CountryEntity, TargetEntityT>? rel, [
    _i5.Condition<TargetEntityT>? qc,
  ]) =>
      throw UnsupportedError(
          r'"linkMany" cannot be used without a mockito fallback generator.');

  @override
  backlinkMany<SourceEntityT>(
    _i5.QueryRelationToMany<SourceEntityT, _i6.CountryEntity>? rel, [
    _i5.Condition<SourceEntityT>? qc,
  ]) =>
      throw UnsupportedError(
          r'"backlinkMany" cannot be used without a mockito fallback generator.');
}
