// Mocks generated by Mockito 5.4.6 from annotations
// in esim_open_source/test/data/repository/api_auth_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:esim_open_source/data/remote/auth_reload_interface.dart' as _i5;
import 'package:esim_open_source/data/remote/unauthorized_access_interface.dart'
    as _i4;
import 'package:esim_open_source/domain/data/api_auth.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [APIAuth].
///
/// See the documentation for Mockito's code generation for more information.
class MockAPIAuth extends _i1.Mock implements _i2.APIAuth {
  MockAPIAuth() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.FutureOr<dynamic> resendOtp({required String? email}) =>
      (super.noSuchMethod(Invocation.method(
        #resendOtp,
        [],
        {#email: email},
      )) as _i3.FutureOr<dynamic>);

  @override
  _i3.FutureOr<dynamic> verifyOtp({
    String? email,
    String? phoneNumber,
    String? pinCode = '',
    String? providerToken = '',
    String? providerType = '',
  }) =>
      (super.noSuchMethod(Invocation.method(
        #verifyOtp,
        [],
        {
          #email: email,
          #phoneNumber: phoneNumber,
          #pinCode: pinCode,
          #providerToken: providerToken,
          #providerType: providerType,
        },
      )) as _i3.FutureOr<dynamic>);

  @override
  void addUnauthorizedAccessListener(
          _i4.UnauthorizedAccessListener? unauthorizedAccessCallBack) =>
      super.noSuchMethod(
        Invocation.method(
          #addUnauthorizedAccessListener,
          [unauthorizedAccessCallBack],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeUnauthorizedAccessListener(
          _i4.UnauthorizedAccessListener? unauthorizedAccessCallBack) =>
      super.noSuchMethod(
        Invocation.method(
          #removeUnauthorizedAccessListener,
          [unauthorizedAccessCallBack],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addAuthReloadListenerCallBack(
          _i5.AuthReloadListener? authReloadListener) =>
      super.noSuchMethod(
        Invocation.method(
          #addAuthReloadListenerCallBack,
          [authReloadListener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeAuthReloadListenerCallBack(
          _i5.AuthReloadListener? authReloadListener) =>
      super.noSuchMethod(
        Invocation.method(
          #removeAuthReloadListenerCallBack,
          [authReloadListener],
        ),
        returnValueForMissingStub: null,
      );
}
