// Mocks generated by Mockito 5.4.6 from annotations
// in esim_open_source/test/data/repository/api_user_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:esim_open_source/data/data_source/esims_local_data_source.dart'
    as _i5;
import 'package:esim_open_source/data/remote/request/related_search.dart'
    as _i4;
import 'package:esim_open_source/data/remote/responses/bundles/purchase_esim_bundle_response_model.dart'
    as _i6;
import 'package:esim_open_source/domain/data/api_user.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ApiUser].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiUser extends _i1.Mock implements _i2.ApiUser {
  MockApiUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.FutureOr<dynamic> getUserConsumption({required String? iccID}) =>
      (super.noSuchMethod(Invocation.method(
        #getUserConsumption,
        [],
        {#iccID: iccID},
      )) as _i3.FutureOr<dynamic>);

  @override
  _i3.FutureOr<dynamic> assignBundle({
    required String? bundleCode,
    required String? promoCode,
    required String? referralCode,
    required String? affiliateCode,
    required String? paymentType,
    required _i4.RelatedSearchRequestModel? relatedSearch,
    String? bearerToken,
  }) =>
      (super.noSuchMethod(Invocation.method(
        #assignBundle,
        [],
        {
          #bundleCode: bundleCode,
          #promoCode: promoCode,
          #referralCode: referralCode,
          #affiliateCode: affiliateCode,
          #paymentType: paymentType,
          #relatedSearch: relatedSearch,
          #bearerToken: bearerToken,
        },
      )) as _i3.FutureOr<dynamic>);

  @override
  _i3.FutureOr<dynamic> topUpBundle({
    required String? iccID,
    required String? bundleCode,
    required String? paymentType,
  }) =>
      (super.noSuchMethod(Invocation.method(
        #topUpBundle,
        [],
        {
          #iccID: iccID,
          #bundleCode: bundleCode,
          #paymentType: paymentType,
        },
      )) as _i3.FutureOr<dynamic>);

  @override
  _i3.FutureOr<dynamic> getUserNotifications({
    required int? pageIndex,
    required int? pageSize,
  }) =>
      (super.noSuchMethod(Invocation.method(
        #getUserNotifications,
        [],
        {
          #pageIndex: pageIndex,
          #pageSize: pageSize,
        },
      )) as _i3.FutureOr<dynamic>);

  @override
  _i3.FutureOr<dynamic> getBundleExists({required String? code}) =>
      (super.noSuchMethod(Invocation.method(
        #getBundleExists,
        [],
        {#code: code},
      )) as _i3.FutureOr<dynamic>);

  @override
  _i3.FutureOr<dynamic> getBundleLabel({
    required String? iccid,
    required String? label,
  }) =>
      (super.noSuchMethod(Invocation.method(
        #getBundleLabel,
        [],
        {
          #iccid: iccid,
          #label: label,
        },
      )) as _i3.FutureOr<dynamic>);

  @override
  _i3.FutureOr<dynamic> getMyEsimByIccID({required String? iccID}) =>
      (super.noSuchMethod(Invocation.method(
        #getMyEsimByIccID,
        [],
        {#iccID: iccID},
      )) as _i3.FutureOr<dynamic>);

  @override
  _i3.FutureOr<dynamic> getMyEsimByOrder({
    required String? orderID,
    String? bearerToken,
  }) =>
      (super.noSuchMethod(Invocation.method(
        #getMyEsimByOrder,
        [],
        {
          #orderID: orderID,
          #bearerToken: bearerToken,
        },
      )) as _i3.FutureOr<dynamic>);

  @override
  _i3.FutureOr<dynamic> getRelatedTopUp({
    required String? iccID,
    required String? bundleCode,
  }) =>
      (super.noSuchMethod(Invocation.method(
        #getRelatedTopUp,
        [],
        {
          #iccID: iccID,
          #bundleCode: bundleCode,
        },
      )) as _i3.FutureOr<dynamic>);

  @override
  _i3.FutureOr<dynamic> getOrderHistory({
    required int? pageIndex,
    required int? pageSize,
  }) =>
      (super.noSuchMethod(Invocation.method(
        #getOrderHistory,
        [],
        {
          #pageIndex: pageIndex,
          #pageSize: pageSize,
        },
      )) as _i3.FutureOr<dynamic>);

  @override
  _i3.FutureOr<dynamic> getOrderByID({required String? orderID}) =>
      (super.noSuchMethod(Invocation.method(
        #getOrderByID,
        [],
        {#orderID: orderID},
      )) as _i3.FutureOr<dynamic>);

  @override
  _i3.FutureOr<dynamic> topUpWallet({
    required double? amount,
    required String? currency,
  }) =>
      (super.noSuchMethod(Invocation.method(
        #topUpWallet,
        [],
        {
          #amount: amount,
          #currency: currency,
        },
      )) as _i3.FutureOr<dynamic>);

  @override
  _i3.FutureOr<dynamic> cancelOrder({required String? orderID}) =>
      (super.noSuchMethod(Invocation.method(
        #cancelOrder,
        [],
        {#orderID: orderID},
      )) as _i3.FutureOr<dynamic>);

  @override
  _i3.FutureOr<dynamic> resendOrderOtp({required String? orderID}) =>
      (super.noSuchMethod(Invocation.method(
        #resendOrderOtp,
        [],
        {#orderID: orderID},
      )) as _i3.FutureOr<dynamic>);

  @override
  _i3.FutureOr<dynamic> verifyOrderOtp({
    required String? otp,
    required String? iccid,
    required String? orderID,
  }) =>
      (super.noSuchMethod(Invocation.method(
        #verifyOrderOtp,
        [],
        {
          #otp: otp,
          #iccid: iccid,
          #orderID: orderID,
        },
      )) as _i3.FutureOr<dynamic>);
}

/// A class which mocks [EsimsLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockEsimsLocalDataSource extends _i1.Mock
    implements _i5.EsimsLocalDataSource {
  MockEsimsLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> replacePurchasedEsims(
          List<_i6.PurchaseEsimBundleResponseModel>? dataList) =>
      (super.noSuchMethod(
        Invocation.method(
          #replacePurchasedEsims,
          [dataList],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
