// Mocks generated by Mockito 5.4.6 from annotations
// in esim_open_source/test/data/repository/api_bundles_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:esim_open_source/data/data_source/home_local_data_source.dart'
    as _i4;
import 'package:esim_open_source/data/remote/responses/bundles/home_data_response_model.dart'
    as _i5;
import 'package:esim_open_source/domain/data/api_bundles.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [APIBundles].
///
/// See the documentation for Mockito's code generation for more information.
class MockAPIBundles extends _i1.Mock implements _i2.APIBundles {
  MockAPIBundles() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.FutureOr<dynamic> getBundleConsumption({required String? iccID}) =>
      (super.noSuchMethod(Invocation.method(
        #getBundleConsumption,
        [],
        {#iccID: iccID},
      )) as _i3.FutureOr<dynamic>);

  @override
  _i3.FutureOr<dynamic> getBundle({required String? code}) =>
      (super.noSuchMethod(Invocation.method(
        #getBundle,
        [],
        {#code: code},
      )) as _i3.FutureOr<dynamic>);

  @override
  _i3.FutureOr<dynamic> getBundlesByRegion({required String? regionCode}) =>
      (super.noSuchMethod(Invocation.method(
        #getBundlesByRegion,
        [],
        {#regionCode: regionCode},
      )) as _i3.FutureOr<dynamic>);

  @override
  _i3.FutureOr<dynamic> getBundlesByCountries(
          {required String? countryCodes}) =>
      (super.noSuchMethod(Invocation.method(
        #getBundlesByCountries,
        [],
        {#countryCodes: countryCodes},
      )) as _i3.FutureOr<dynamic>);
}

/// A class which mocks [HomeLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeLocalDataSource extends _i1.Mock
    implements _i4.HomeLocalDataSource {
  MockHomeLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveHomeData(_i5.HomeDataResponseModel? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveHomeData,
          [data],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
